config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'site#home'
  
  devise_for :admins 
  
  get "site/about"
  get "site/contact"
  get "site/portfolio"
  get "site/home"
  get "site/client"
  get "/site/gallery_newborns"
  get "site/gallery_maternity"
  get "site/gallery_children"
  
  get '/about' => 'site#about'
  get '/contact' => 'site#contact'
  get '/portfolio'=>'site#portfolio'
  get '/home' =>'site#home'
  #get '/client' => 'site#client'
  get '/gallery_children' =>'site#gallery_children'
  get '/gallery_maternity' =>'site#gallery_maternity'
  get '/gallery_newborns' =>'site#gallery_newborns'
  get '/home_slidgallery' => 'site#home_slidgallery'
  get '/client' => 'items#index'
  
 
 get "users/mailer"
 get 'orderitems/index'
 get 'orderitems/show'
 get 'orderitems/new'
 get 'orderitems/edit'

 resources :orderitems
 # resources :cart

devise_for :users do
    resources :orders
end

 
 #get "/login" => "users/sessions#new"
 get "/register" => "users/registrations#new"
 #get "/users/sign_out" => "devise/sessions#destroy"

 resources :orders do
  resources :orderitems  
end
  
 get "cart/index"
resources :users
 resources :items
 
 authenticated :user do
  root 'items#index', as: "authenticated_root"
 end 
 
 get '/cart' => 'cart#index'
 get 'cart/clear' => 'cart#clearCart'
 
 get '/cart/:id' => 'cart#add'
 post '/add_to_cart/:product_id' => 'cart#add_to_cart', :as => 'add_to_cart'
 get "/cart/:id" => "create#Order"
 get '/cart/remove/:id' => 'cart#remove'
 
 get '/checkout' => 'cart#controller'
 get '/checkout' => 'cart#createOrder'
 get '/Admin' => 'user#admin_login'
 #get '/logout' => 'user#logout'
  
 
 

end

app/models/item.rb
class Item < ActiveRecord::Base
      belongs_to :user
      belongs_to :cart
      
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.where(user_id: current_user)
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = current_user.items.build
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.build(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :category)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Photos & Frames</h1>
<table class="catalog">
<% @items.each do |item| %>
  
  <tr>
    <td>
      <div class="image">
        <%= link_to (image_tag item.image_url, :style => "height:100px"), item %>
      </div>
      
  </td>
    <td>
      <div class="title">
        <%= link_to item.title, item %>
      </div>
      
      <div class="description">
        <%=h item.description %>
      </div>

      <div class="price">
        <%= number_to_currency(item.price, :unit => "€") %>
      </div>
          
      
      <div class="links">
        <%= link_to 'Edit', edit_item_path(item) %> |
        <%= link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete %>
      </div>
        <td><a href="/cart/<%= item.id %>">Add to Cart</a></td>
        
      
    </td>
  </tr>

<% end %>
</table>
<p><%= link_to 'New item', new_item_path %></p>


<p id="notice"><%= notice %></p>

</body>
</html>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @item.image_url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>